kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubechain-role
rules:
- apiGroups: ["kubechain.com"] 
  resources: ["blocks"]
  verbs: ["get", "watch", "list", "create", "patch", "update"]
